awesome_blogs/awesome_blogs/users/urls.py
from django.urls import path

from awesome_blogs.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

awesome_blogs/blogs/urls.py
from django.urls import path

from .views import (FeedView, UserPostsView, MyPostsView, 
    AddPostView, DetailPostView, SubscriptionsView, MarkReadView,
    UnMarkReadView, DeletePostView, UpdatePostView
    )


app_name = 'blogs'
urlpatterns = [
    path('users/<str:username>/', UserPostsView.as_view(), name='userposts'),
    path('feed/<int:pk>/unread/', UnMarkReadView.as_view(), name='unread'),
    path('feed/<int:pk>/read/', MarkReadView.as_view(), name='read'),
    path('feed/', FeedView.as_view(), name='feed'),
    path('subscriptions/', SubscriptionsView.as_view(), name='subscriptions'),
    path('my/', MyPostsView.as_view(), name='myposts'),
    path('add/', AddPostView.as_view(), name='add'),
    path('detail/<int:pk>/delete/', DeletePostView.as_view(), name='delete'),
    path('detail/<int:pk>/update/', UpdatePostView.as_view(), name='update'),
    path('detail/<int:pk>/', DetailPostView.as_view(), name='detail'),
]

awesome_blogs/awesome_blogs/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    name = models.CharField(_("Name of User"), blank=True, max_length=255,
        unique=True)
    email = models.EmailField(verbose_name='Е-mail пользователя')

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

awesome_blogs/awesome_blogs/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

awesome_blogs/awesome_blogs/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

awesome_blogs/awesome_blogs/templates/pages/about.html
{% extends "base.html" %}

awesome_blogs/awesome_blogs/templates/pages/create_post.html
{% extends "base.html" %}

{% block content %}

<h2>Создание нового поста</h2>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить">
</form>

{% endblock content %}

awesome_blogs/awesome_blogs/templates/pages/delete_confirm_post.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid mb-2 p-3">
    <h2>Удаление поста</h2>
    <p class="text-right font-weight-bold">
        Автор: {{ post.title }}
    </p>
    <p class="text-right font-weight-bold">
        Автор: {{ post.author }}
    </p>
    <p class="text-right font-italic">
        Опубликовано: {{ post.created_at }}
    </p>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Удалить">
    </form>
</div>
{% endblock content %}

awesome_blogs/awesome_blogs/templates/pages/feed.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid mb-2 p-3">
    <h2>Моя лента</h2>
    <ul class="list-unstyled">
        {% for feed in feeds %}
        <li class="my-5 p-3 border">
            <a href="{% url 'blogs:detail' pk=feed.post.pk %}">{{ feed.post.title }}</a>
            {% if feed.read  %}
                <p class="font-italic">Прочитано</p>
                <form action="{% url 'blogs:unread' pk=feed.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="Отметить непрочитанным">    
                </form>
            {% else %}
                <p class="font-weight-bold">Непрочитано</p>
                <form action="{% url 'blogs:read' pk=feed.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="Отметить прочитанным">    
                </form>
            {% endif  %}
            <p class="text-right font-weight-bold">
                Автор: <a href="{% url 'blogs:userposts' feed.post.author.name %}">{{ feed.post.author.name }}</a>
            </p> 
            <p class="text-right font-italic">Опубликовано: {{ feed.post.created_at }}</p>   
        </li>
        {% endfor %}
    </ul>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
    
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
            {% endif %}
    
            {% for i in page_range %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endfor %}
    
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
            {% endif %}

        </ul>
    </nav>
</div>
{% endblock content %}

awesome_blogs/awesome_blogs/templates/pages/home.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid mb-2 p-3">
    <h2>Все посты</h2>
    <ul class="list-unstyled">
        {% for post in posts %}
        <li class="my-5 p-3 border">
            <a href="{% url 'blogs:detail' pk=post.pk %}">{{ post.title }}</a>
            <p class="text-right font-weight-bold">
                Автор: <a href="{% url 'blogs:userposts' post.author.name %}">{{ post.author.name }}</a>
            </p> 
            <p class="text-right font-italic">Опубликовано: {{ post.created_at }}</p>   
        </li>
        {% endfor %}
    </ul>

    <nav aria-label="Page navigation example">
        <ul class="pagination">
    
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
            {% endif %}
    
            {% for i in page_range %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endfor %}
    
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
            {% endif %}

        </ul>
    </nav>

</div>
{% endblock content %}

awesome_blogs/awesome_blogs/templates/pages/post_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid mb-2 p-3">
    <h2>{{ post.title }}</h2>
    <p class="text-right font-weight-bold">
        Автор: {{ post.author }}
    </p>
    <p class="border p-3">
        {{ post.content }}
    </p>
    <p class="text-right font-italic">
        Опубликовано: {{ post.created_at }}
    </p>
    {% if request.user.is_authenticated %}
        {% if request.user == post.author %}
        <p>
            <a href="{% url 'blogs:delete' pk=post.pk %}">Удалить</a>
            <a href="{% url 'blogs:update' pk=post.pk %}">Изменить</a>
        </p>   
        {% endif %}
    {% endif %}
</div>
{% endblock content %}

awesome_blogs/awesome_blogs/templates/pages/post_list.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid mb-2 p-3">
    <h2>Все посты пользователя {{ username }}</h2>
    <ul class="list-unstyled">
        {% for post in posts %}
        <li class="my-5 p-3 border">
            <a href="{% url 'blogs:detail' pk=post.pk %}">{{ post.title }}</a>
            <p class="text-right font-weight-bold">
                Автор: <a href="{% url 'blogs:userposts' post.author.name %}">{{ post.author.name }}</a>
            </p> 
            <p class="text-right font-italic">Опубликовано: {{ post.created_at }}</p>   
        </li>
        {% endfor %}
    </ul>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
    
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
            {% endif %}
    
            {% for i in page_range %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endfor %}
    
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
            {% endif %}

        </ul>
    </nav>
</div>
{% endblock content %}

awesome_blogs/awesome_blogs/templates/pages/subscriptions.html
{% extends "base.html" %}

{% block content %}

<h2>Мои подписки</h2>

<form method="POST">
    {% csrf_token %}
    {{ formset.as_p }}
    <input type="submit" value="Сохранить">
</form>

{% endblock content %}